import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {DemoModel,ensureStorePackageExamples} from './core.js';
import {ensureEvaluations} from './evaluations.js';
import {ensurePaperIntakes} from './paper-intake.js';
import {renderStaff} from './staff.js';
import {cashDialog} from './cash.js';
import {bossDecisionSummary,bossDecisionDialog,renderBossDecision} from './boss-decision.js';
const boss={type:'boss',id:'boss'};
const source=await readFile(new URL('./app.js',import.meta.url),'utf8');
const m=()=>ensurePaperIntakes(ensureEvaluations(ensureStorePackageExamples(new DemoModel({now:()=> '2026-10-08T08:00:00.000Z'}))));
const ctx=(model,role=boss,filters={})=>({model,role,filters,view:'overview',icon:()=>'',esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))});
function route(context){const scope={bossDecisionDialog,cashDialog,model:context.model,role:context.role,workflowTypes:new Set(),customerBookingTypes:new Set(),evaluationTypes:new Set(),staffTypes:new Set(),ctx:()=>context};const start=source.indexOf('function buildDialog('),end=source.indexOf('\nfunction draftKey',start);vm.runInNewContext(source.slice(start,end),scope);return scope.buildDialog;}
function clicks(context){const scope={document:{addEventListener(name,handler){if(name==='click')scope.click=handler;}},openDialog:(action,id)=>{scope.result=route(context)(action,id);},toast:e=>{scope.error=e;}};const start=source.indexOf("document.addEventListener('click', event =>"),end=source.indexOf('\nfunction checkReceptionIntakePhone',start);vm.runInNewContext(source.slice(start,end),scope);return scope;}
test('boss overview places exactly three clear decision cards before cash figures',()=>{const context=ctx(m()),html=renderStaff(context);assert.equal((html.match(/data-action="boss-decision-detail"/g)||[]).length,3);assert.ok(html.indexOf('老板今日决策')<html.indexOf('cash-hero'));assert.match(html,/固定今天，不受下方业绩日期或康复师筛选影响/);assert.match(html,/收款录入|收款.*核对/);assert.match(html,/虚构|示例/);});
test('cash and revenue detail keep current day and selected store despite unrelated period and staff filters',()=>{const model=m();model.recordReceipt({clientId:'c3',storeId:'a',purpose:'single',channel:'direct',method:'wechat',amount:'400',date:model.today,time:'10:00',requestId:'today'},boss);const context=ctx(model,boss,{storeId:'a',from:'2020-01-01',to:'2020-01-01',therapistId:'t2'});const html=bossDecisionDialog('revenue',context).html;assert.match(html,/¥400\.00/);assert.doesNotMatch(html,/崂山店|2020-01-01|上涨|下降|增长率/);assert.match(html,/无登记日按 0.*不代表.*真实营业额/);assert.match(html,/收支明细（当前筛选）/);const cash=bossDecisionDialog('cash',context).html;assert.ok(cash.includes('&quot;storeId&quot;:&quot;a&quot;'));assert.ok(cash.includes('&quot;date&quot;:&quot;2026-10-08&quot;'));});
test('new card action actually dispatches through the app click and dialog handlers',()=>{const context=ctx(m()),scope=clicks(context);scope.click({target:{closest:()=>({dataset:{action:'boss-decision-detail',id:'cash'}})}});assert.equal(scope.error,undefined);assert.equal(scope.result.title,'把收款录入核对清楚');assert.match(scope.result.html,/data-action="cash-closing"/);for(const role of [{type:'frontdesk',id:'f1'},{type:'manager',id:'m1'},{type:'customer',id:'c1'},{type:'therapist',id:'t1'},{type:'boss',id:'wrong'}]){const denied=clicks(ctx(m(),role));denied.click({target:{closest:()=>({dataset:{action:'boss-decision-detail',id:'cash'}})}});assert.match(denied.error,/老板|权限/);assert.equal(denied.result,undefined);}});
test('record actions reuse real closing form and receipt detail routes rather than a fake done flag',()=>{const model=m(),context=ctx(model);model.recordReceipt({clientId:'c3',storeId:'a',purpose:'package',channel:'direct',method:'wechat',amount:'400',date:model.today,time:'10:00',requestId:'trace'},boss);const item=bossDecisionSummary(model,boss).items[0];assert.ok(item.evidence.some(r=>r.action==='receipt-detail'));assert.ok(item.evidence.some(r=>r.action==='cash-closing'));const html=bossDecisionDialog('cash',context).html;assert.doesNotMatch(html,/data-action="dismiss|data-form="boss-decision|mark.*done/);assert.match(source,/if\(type==='boss-decision-detail'\)return bossDecisionDialog\(id,ctx\(\)\)/);assert.match(source,/\['link-receipt-package','cash-closing','cash-closing-confirm'\].*cashDialog/);});
test('dynamic record names, labels, employee names and route ids are escaped',()=>{const model=m();model.state.clients.find(r=>r.id==='c3').name='<script>bad</script>';model.state.stores.find(r=>r.id==='a').name='<img bad>';model.state.therapists.find(r=>r.id==='t1').name='<svg bad>';model.state.tasks.push({id:'" onclick="bad',clientId:'c3',storeId:'a',assigneeId:'t1',dueDate:'2026-10-01',status:'pending',title:'<iframe bad>'});const html=bossDecisionDialog('flow',ctx(model)).html;assert.match(html,/&lt;script&gt;/);assert.match(html,/&lt;img/);assert.match(html,/&lt;svg/);assert.match(html,/&quot; onclick=&quot;/);assert.doesNotMatch(html,/<script>|<img bad>|<svg bad>|<iframe bad>/);});
test('large evidence lists render at most 30 records but preserve the true total',()=>{const model=m();model.state.assessments=[];model.state.paperIntakes=[];model.state.appointments=[];model.state.tasks=Array.from({length:95},(_,i)=>({id:'late-'+i,clientId:'c3',storeId:'a',assigneeId:'t1',dueDate:'2026-10-01',status:'pending',title:'待办'+i}));const html=bossDecisionDialog('flow',ctx(model)).html;assert.equal((html.match(/class="boss-decision-evidence"/g)||[]).length,30);assert.match(html,/95 条流程记录|共 95 条依据/);assert.equal(bossDecisionSummary(model,boss).items[1].count,95);});
test('other staff pages contain no private decision window and forged boss rendering refuses',()=>{const model=m();for(const role of [{type:'frontdesk',id:'f1'},{type:'manager',id:'m1'},{type:'customer',id:'c1'},{type:'therapist',id:'t1'}])assert.equal(renderBossDecision(ctx(model,role)),'');assert.throws(()=>renderBossDecision(ctx(model,{type:'boss',id:'wrong'})),/老板|权限/);});
test('phone styles retain readable cards, 44px record actions and no remote font or AI dependencies',async()=>{const css=await readFile(new URL('./boss-decision.css',import.meta.url),'utf8'),js=await readFile(new URL('./boss-decision.js',import.meta.url),'utf8');assert.match(css,/@media\(max-width:760px\)/);assert.match(css,/min-height:44px/);assert.match(css,/font-size:16px/);assert.doesNotMatch(css+js,/https?:\/\/|@import|fetch\(/);assert.match(source,/previewEntry==='boss'\)switchRole\('boss:boss'\)/);});

test('each cash evidence action routes through the actual app buildDialog into the real cash form',()=>{
 const model=m(),context=ctx(model),routeTo=route(context);model.recordReceipt({clientId:'c3',storeId:'a',purpose:'package',channel:'direct',method:'wechat',amount:'400',date:model.today,time:'10:00',requestId:'actual-route'},boss);const e=bossDecisionSummary(model,boss).items[0].evidence;for(const row of e){const target=routeTo(row.action,row.actionId);assert.ok(target.html);if(row.action==='cash-closing'){assert.equal(target.title,'每日营业对账');assert.match(target.html,/data-form="cash-closing"/);assert.ok(target.html.includes(row.date));}else if(row.action==='receipt-detail'){assert.match(target.html,/已到账|套餐待关联/);assert.ok(target.html.includes('400'));}}
});
