import test from 'node:test';import assert from 'node:assert/strict';
import {DemoModel} from './legacy-test-fixture.mjs';import {confirmedTestSchedules} from './scheduling-test-fixture.mjs';
const boss={type:'boss',id:'boss'},fa={type:'frontdesk',id:'f1'},fb={type:'frontdesk',id:'f2'},ma={type:'manager',id:'m1'},mb={type:'manager',id:'m2'},t1={type:'therapist',id:'t1'};
const fresh=()=>confirmedTestSchedules(new DemoModel({today:'2026-10-08',now:()=> '2026-10-08T08:00:00Z'}));
const before=m=>JSON.stringify([m.state,m.sequence]);const denied=(m,f,re)=>{const b=before(m);assert.throws(f,re);assert.equal(before(m),b);};
test('front desk cancel only requests approval and local manager approves exactly once',()=>{const m=fresh(),a=m.cancelAppointment('a3','客户改期',fa,{requestId:'cancel'});assert.equal(a.status,'confirmed');assert.equal(a.cancellationRequest.status,'pending');assert.equal(a.cancellationRequest.source,'frontdesk');assert.equal(a.cancellationRequest.requestedRole,'frontdesk');assert.equal(a.cancellationRequest.needsApproval,true);const original=before(m);m.cancelAppointment('a3','客户改期',fa,{requestId:'cancel'});assert.equal(before(m),original);const done=m.handleAppointmentCancellation('a3',{decision:'approve',reason:'已核对，同意',requestId:'approve'},ma);assert.equal(done.status,'cancelled');assert.equal(done.cancellationRequest.status,'approved');assert.equal(done.cancellationRequest.handledRole,'manager');assert.equal(done.cancellationRequest.handledBy,'m1');const final=before(m);m.handleAppointmentCancellation('a3',{decision:'approve',reason:'已核对，同意',requestId:'approve'},ma);assert.equal(before(m),final);});
test('boss can cancel both stores and manager only local appointments',()=>{for(const id of ['a3','a1']){const m=fresh();assert.equal(m.cancelAppointment(id,'老板直接取消',boss).status,'cancelled');}const m=fresh();denied(m,()=>m.cancelAppointment('a1','跨店',ma),/本店|权限/);assert.equal(m.cancelAppointment('a3','本店取消',ma).status,'cancelled');});
test('frontdesk accepting a customer cancellation stays pending approval and cannot self approve',()=>{const m=fresh();m.requestAppointmentCancellation('a3',{reason:'客户取消',requestId:'customer'},{type:'customer',id:'c3'});const row=m.handleAppointmentCancellation('a3',{decision:'approve',reason:'前台核对并申请批准',requestId:'forward'},fa);assert.equal(row.status,'confirmed');assert.equal(row.cancellationRequest.status,'pending');assert.equal(row.cancellationRequest.source,'customer');assert.equal(row.cancellationRequest.approvalRequestedRole,'frontdesk');assert.equal(row.cancellationRequest.needsApproval,true);denied(m,()=>m.handleAppointmentCancellation('a3',{decision:'approve',reason:'自批'},fa),/审批|老板|店长/);denied(m,()=>m.handleAppointmentCancellation('a3',{decision:'approve',reason:'跨店审批'},mb),/本店|权限/);assert.equal(m.handleAppointmentCancellation('a3',{decision:'reject',reason:'暂保留'},ma).status,'confirmed');assert.equal(m.state.appointments.find(a=>a.id==='a3').cancellationRequest.status,'rejected');m.recordArrival('a3',{requestId:'arrival'},fb);});
test('pending approval retains time and rejects arrival, edit, reschedule, no-show, explicit and implicit services atomically',()=>{const m=fresh();m.cancelAppointment('a3','申请取消',fa);const a=m.state.appointments.find(a=>a.id==='a3');for(const run of [()=>m.recordArrival('a3',{requestId:'arrival'},boss),()=>m.saveAppointment({...a,time:'15:00'},boss),()=>m.requestReschedule('a3',{date:'2026-10-09',time:'15:00',reason:'改约'},{type:'customer',id:'c3'}),()=>m.markNoShow('a3','没到',boss)])denied(m,run,/取消|审批/);const input={clientId:'c3',storeId:'a',date:m.today,time:'14:00',principalId:'t1',project:'阶段复评',notes:'本次情况',requestId:'service',evidencePhotos:[{id:'photo',name:'photo.jpg',dataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=',width:1,height:1}]};for(const extra of [{},{appointmentId:'a3'}])denied(m,()=>m.registerService({...input,...extra},t1),/取消|审批/);denied(m,()=>m.saveAppointment({clientId:'c1',storeId:'a',date:m.today,time:'14:30',principalId:'t1',project:'冲突'},boss),/冲突/);});
test('revoked and cross-store staff cannot submit or replay approval, and request history remains',()=>{const m=fresh();denied(m,()=>m.cancelAppointment('a3','错店',fb),/权限|门店/);m.cancelAppointment('a3','申请',fa,{requestId:'r'});denied(m,()=>m.handleAppointmentCancellation('a3',{decision:'approve',reason:'主治疗师替批'},t1),/审批|老板|店长/);m.state.storeManagers.find(p=>p.id==='m1').active=false;denied(m,()=>m.handleAppointmentCancellation('a3',{decision:'approve',reason:'停用'},ma),/权限|店长/);m.handleAppointmentCancellation('a3',{decision:'reject',reason:'拒绝'},boss);m.cancelAppointment('a3','新申请',fa,{requestId:'r2'});assert.equal(m.state.appointments.find(a=>a.id==='a3').cancellationHistory[0].status,'rejected');m.state.frontDesks[0].active=false;denied(m,()=>m.cancelAppointment('a3','新申请',fa,{requestId:'r2'}),/在职|停用/);});

test('a pending frontdesk cancellation cannot be bypassed by direct principal cancellation',()=>{const m=fresh();m.cancelAppointment('a3','待批准',fa,{requestId:'r'});assert.equal(m.cancellationPermissions(t1,m.state.appointments.find(a=>a.id==='a3')).canCancel,false);denied(m,()=>m.cancelAppointment('a3','主治疗师直取消',t1),/审批|老板|店长/);const done=m.cancelAppointment('a3','本店批准',ma,{requestId:'direct-approved'});assert.equal(done.cancellationRequest.status,'approved');assert.equal(done.cancelByRole,'manager');assert.equal(done.cancelById,'m1');assert.ok(done.cancelAt);});
test('frontdesk forwarding is idempotent but no new approval decision is authorized',()=>{const m=fresh();m.requestAppointmentCancellation('a3',{reason:'客户取消'},{type:'customer',id:'c3'});const data={decision:'approve',reason:'核对后报批',requestId:'forward'};m.handleAppointmentCancellation('a3',data,fa);const b=before(m);m.handleAppointmentCancellation('a3',data,fa);assert.equal(before(m),b);denied(m,()=>m.handleAppointmentCancellation('a3',{...data,requestId:'other'},fa),/审批|老板|店长/);m.state.frontDesks[0].active=false;denied(m,()=>m.handleAppointmentCancellation('a3',data,fa),/在职|停用/);});

test('implicit service cannot replace a pending cancellation principal to bypass approval',()=>{
 const m=fresh();m.cancelAppointment('a3','待审批',fa);
 const evidencePhotos=[{id:'p',name:'p.png',width:1,height:1,dataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='}];
 denied(m,()=>m.registerService({clientId:'c3',storeId:'a',date:m.today,time:'14:00',principalId:'t3',project:'阶段复评',notes:'本次情况',requestId:'implicit-other',evidencePhotos},boss),/取消|审批/);
});
