import test from 'node:test';
import assert from 'node:assert/strict';
import {DemoModel} from './core.js';
import {confirmedTestSchedules} from './scheduling-test-fixture.mjs';
import {requestCustomerBooking,confirmCustomerBooking,customerBookingRows} from './customer-booking.js';
import {savePaperIntake,reviewPaperIntake,PAPER_SAFETY_QUESTIONS,paperIntakeRows,paperIntakeDialog} from './paper-intake.js';
import {recordAssessment,confirmAssessment,assessmentRows,evaluationDialog} from './evaluations.js';
import {staffReceptionDialog,renderStaffReception,updateAssessorChoices} from './staff-reception.js';
import {receptionIntakeDialog} from './reception.js';
const boss={type:'boss',id:'boss'},front={type:'frontdesk',id:'f1'};
const staff=[boss,front,{type:'frontdesk',id:'f2'},{type:'manager',id:'m-chen-kang'},{type:'manager',id:'m-he-zanfeng'},{type:'therapist',id:'t-qiu-zhen'},{type:'therapist',id:'t-zou-zonglin'},{type:'therapist',id:'t-wu-wenpei'}];
const fresh=()=>confirmedTestSchedules(new DemoModel({today:'2026-10-08',now:()=> '2026-10-08T06:00:00Z'}));
const create=m=>m.createReceptionClient({name:'虚构客户',phone:'13912345678',age:32,storeId:'a',requestId:'new'},front);
const ctx=(m,role)=>({model:m,role,filters:{storeId:'a'},esc:String,icon:()=>'',fmt:{date:String},ui:{name:(k,id)=>m.state[k]?.find(p=>p.id===id)?.name||'',button:(l,t,id)=>`<button data-action="${t}" data-id="${id}">${l}</button>`,link:()=>''}});
const request=(m,c)=>requestCustomerBooking(m,{storeId:'a',date:m.today,time:'10:00',principalId:'t-qiu-zhen',project:'基础训练',requestId:'request'},{type:'customer',id:c.id});
const paper=(c,a,extra={})=>({clientId:c.id,appointmentId:a.id,storeId:'a',age:32,assessorId:'m-chen-kang',problem:'本次客户自述',goal:'本次目标',answers:Object.fromEntries(PAPER_SAFETY_QUESTIONS.map(q=>[q.key,'no'])),requestId:'paper',...extra});
const assessment=(c,extra={})=>({clientId:c.id,storeId:'a',assessorId:'m-chen-kang',date:'2026-10-08',time:'10:00',type:'initial',project:'实际评估',metricName1:'活动度',metricValue1:'90',metricUnit1:'度',summary:'实际观察',requestId:'assessment',...extra});
test('actual per-store assessors default to Wang without a fictitious boss therapist',()=>{const m=fresh(),c=create(m);assert.equal(c.assessorId,'tao');assert.equal(c.ownerId,'');assert.deepEqual(m.assessorRows('a').map(p=>p.name),['王勤涛','陈康','邱振','邹宗霖']);assert.deepEqual(m.assessorRows('b').map(p=>p.name),['王勤涛','何赞峰','武文沛']);assert.ok(!m.state.therapists.some(p=>p.id==='tao'||p.id==='t-tao'));assert.throws(()=>m.createReceptionClient({name:'错店',phone:'13912345679',age:32,storeId:'a',assessorId:'m-he-zanfeng',requestId:'bad'},front),/本店/);});
for(const role of staff)test(`all active staff can confirm and receive across stores: ${role.type}/${role.id}`,()=>{const m=fresh(),c=create(m);c.problem='PRIVATE HISTORICAL CLINICAL';const before=m.canSeeClient(role,c.id),r=request(m,c);assert.equal(customerBookingRows(m,role).some(p=>p.id===r.id),true);const done=confirmCustomerBooking(m,r.id,role),a=m.state.appointments.find(p=>p.id===done.appointmentId);assert.equal(done.confirmedBy,role.id);m.recordArrival(a.id,{requestId:'arrival'},role);const dialog=staffReceptionDialog('staff-intake-create',a.id,ctx(m,role));assert.match(dialog.html,/name="appointmentId"/);assert.doesNotMatch(dialog.html,/PRIVATE HISTORICAL CLINICAL/);const row=savePaperIntake(m,paper(c,a),role);assert.equal(row.assessorId,'m-chen-kang');assert.equal(paperIntakeRows(m,role).some(p=>p.id===row.id),true);assert.match(paperIntakeDialog('paper-intake-detail',row.id,ctx(m,role)).html,/本次客户自述/);if(role.id!=='t-qiu-zhen')assert.equal(m.canSeeClient(role,c.id),before);assert.equal(c.ownerId,'');assert.ok(!renderStaffReception(ctx(m,role)).includes('PRIVATE HISTORICAL CLINICAL'));});
test('selected manager and therapist record and confirm their own assessment only',()=>{for(const role of staff.filter(p=>['manager','therapist'].includes(p.type))){const m=fresh(),storeId=role.id==='m-he-zanfeng'||role.id==='t-wu-wenpei'?'b':'a';const c=m.createReceptionClient({name:'本人评估客户',phone:'13912345678',age:32,storeId,assessorId:role.id,requestId:'new'},boss);const payload=assessment(c,{storeId,assessorId:role.id});assert.match(evaluationDialog('assessment-create',c.id,{...ctx(m,role),filters:{storeId}}).html,/name="assessorId"/);const row=recordAssessment(m,payload,role);assert.equal(confirmAssessment(m,row.id,role).confirmedBy,role.id);assert.throws(()=>recordAssessment(m,{...payload,assessorId:'tao',requestId:'other'},role),/本人/);const other=recordAssessment(m,{...payload,assessorId:'tao',requestId:'tao'},boss);assert.throws(()=>confirmAssessment(m,other.id,role),/权限|确认|查看/);assert.equal(assessmentRows(m,role).filter(p=>p.assessorId===role.id).length,1);}});
test('new reception does not grant edits, cancellations, no-show, cash or other clinical history',()=>{const m=fresh(),c=create(m),role={type:'manager',id:'m-he-zanfeng'},r=request(m,c),done=confirmCustomerBooking(m,r.id,role),a=m.state.appointments.find(p=>p.id===done.appointmentId);for(const run of [()=>m.saveAppointment({...a,time:'11:00'},role),()=>m.cancelAppointment(a.id,'取消',role),()=>m.markNoShow(a.id,'未到店',role),()=>m.recordReceipt({clientId:c.id,storeId:'a',amount:100},role),()=>m.publishPlan(c.id,{goal:'目标'},role)])assert.throws(run);assert.equal(m.canSeeClient(role,c.id),false);for(const id of ['',null,false,0,undefined])assert.throws(()=>m.saveAppointment({...a,id},role),/标识/);});
test('request must be confirmed and cancellation resolved before current-day reception',()=>{const m=fresh(),c=create(m),r=request(m,c),role={type:'therapist',id:'t-wu-wenpei'};assert.throws(()=>m.recordArrival(r.id,{requestId:'early'},role),/不存在/);const done=confirmCustomerBooking(m,r.id,role),a=m.state.appointments.find(p=>p.id===done.appointmentId);a.cancellationRequest={status:'pending'};assert.throws(()=>m.recordArrival(a.id,{requestId:'pending'},role),/取消/);a.cancellationRequest.status='rejected';m.recordArrival(a.id,{requestId:'arrive'},role);a.date='2026-10-09';assert.throws(()=>savePaperIntake(m,paper(c,a),role),/今天/);});
test('three intake forms use per-store roster; onchange preserves legal assessor and never changes principal',()=>{const m=fresh(),c=create(m);for(const formType of ['reception-create-client','paper-intake-create','assessment-create']){const select={value:'t-qiu-zhen',innerHTML:''},principal={value:'t-zou-zonglin'},form={dataset:{form:formType},elements:{assessorId:select,storeId:{value:'a'},principalId:principal}};updateAssessorChoices(form,ctx(m,front));assert.equal(select.value,'t-qiu-zhen');form.elements.storeId.value='b';updateAssessorChoices(form,ctx(m,front));assert.equal(select.value,'tao');assert.match(select.innerHTML,/王勤涛/);assert.doesNotMatch(select.innerHTML,/陈康|邱振|邹宗霖/);assert.equal(principal.value,'t-zou-zonglin');}assert.match(receptionIntakeDialog('reception-create-client','a',ctx(m,front)).html,/name="assessorId"/);assert.match(evaluationDialog('assessment-create',c.id,ctx(m,front)).html,/王勤涛/);});

test('fresh historical seed client can use current appointment reception without reviving retired owner',()=>{const m=fresh(),c=m._client('c1'),owner=c.ownerId;assert.equal(c.assessorId,undefined);const r=request(m,c),done=confirmCustomerBooking(m,r.id,{type:'manager',id:'m-he-zanfeng'}),a=m.state.appointments.find(p=>p.id===done.appointmentId),role={type:'therapist',id:'t-wu-wenpei'};m.recordArrival(a.id,{requestId:'seed-arrival'},role);const dialog=staffReceptionDialog('staff-intake-create',a.id,ctx(m,role));assert.match(dialog.html,/王勤涛/);assert.match(dialog.html,/name="assessorId"/);const row=savePaperIntake(m,paper(c,a,{assessorId:'tao'}),role);assert.equal(row.assessorId,'tao');assert.equal(c.ownerId,owner);assert.equal(m.state.therapists.find(t=>t.id===owner).active,false);});
test('shared staff new booking dialog is minimal and offers only a new appointment',()=>{const m=fresh(),role={type:'manager',id:'m-he-zanfeng'},dialog=staffReceptionDialog('staff-booking-create','',ctx(m,role));assert.match(dialog.html,/data-form="appointment-create"/);assert.match(dialog.html,/data-staff-reception="true"/);assert.doesNotMatch(dialog.html,/name="id"|name="ownerId"|收款金额|套餐余额|服务历史/);const c=create(m),a=m.saveAppointment({clientId:c.id,storeId:'a',date:m.today,time:'10:00',principalId:'t-qiu-zhen',project:'训练'},role);assert.equal(a.status,'confirmed');assert.equal(m.canSeeClient(role,c.id),false);});

test('broader new-booking permission does not allow a therapist to transfer an existing appointment to another principal',()=>{const m=fresh(),c=create(m),qiu={type:'therapist',id:'t-qiu-zhen'},a=m.saveAppointment({clientId:c.id,storeId:'a',date:m.today,time:'10:00',principalId:qiu.id,project:'训练'},front),before=JSON.stringify(m.state);assert.throws(()=>m.saveAppointment({...a,principalId:'t-zou-zonglin'},qiu),/本人/);assert.equal(JSON.stringify(m.state),before);});

test('selected manager paper reviewer uses the actual manager name and current assessor header follows selection',()=>{const m=fresh(),c=create(m),a=m.saveAppointment({clientId:c.id,storeId:'a',date:m.today,time:'10:00',principalId:'t-qiu-zhen',project:'训练'},front);m.recordArrival(a.id,{requestId:'arrival'},front);const row=savePaperIntake(m,paper(c,a),front),chen={type:'manager',id:'m-chen-kang'};reviewPaperIntake(m,row.id,{decision:'assessment',nextStep:'本人评估',assigneeId:'boss',dueDate:m.today,requestId:'review'},chen);assert.match(paperIntakeDialog('paper-intake-detail',row.id,ctx(m,chen)).html,/复核人 陈康/);const html=staffReceptionDialog('staff-intake-create',a.id,ctx(m,front)).html;assert.match(html,/本次评估师 <span data-paper-assessor-name>/);assert.doesNotMatch(html,/负责康复师 王勤涛/);const label={textContent:''},form={dataset:{form:'paper-intake-create'},elements:{storeId:{value:'a'},assessorId:{value:'m-chen-kang',innerHTML:''}},querySelector:()=>label};updateAssessorChoices(form,ctx(m,front));assert.equal(label.textContent,'陈康');form.elements.storeId.value='b';updateAssessorChoices(form,ctx(m,front));assert.equal(label.textContent,'王勤涛');});

test('assessment recorder and confirmer names resolve by their actual account roles',async()=>{const m=fresh(),c=create(m),chen={type:'manager',id:'m-chen-kang'},row=recordAssessment(m,assessment(c),chen),html=evaluationDialog('assessment-confirm',row.id,ctx(m,chen)).html;assert.match(html,/评估师 陈康 · 录入 陈康/);assert.doesNotMatch(html,/录入 历史人员|待康复师确认/);});
